### ISSUE TITLE
Overhaul HTML

### ISSUE THREAD

**Issue by odysseuskir** [simplified-coding/simplified-coding#113]
**Is your feature request related to a problem? Please describe.**
I have noticed lately that the courses Simplified Coding often are unclear and confusing to people just starting with programming. That is why I am proposing a much-needed overhaul to all courses, to refresh the lessons and put the beginner in mind.

**Describe the solution you'd like**
The lessons should have clear examples, a similar format, and tone, to make them easier to comprehend and more fun to go through.

**Describe alternatives you've considered**
A temporary solution could be a quick rundown of each lesson until an overhaul has begun

**Additional context**
N/A

**Comment by GalaxyGamingBoy** [comment]
A standard reference guide is needed, a complete overhaul is unjustified
