### ISSUE TITLE
Overhaul lesson view page & better course data

### ISSUE THREAD

**Issue by odysseuskir** [simplified-coding/simplified-coding#114]
**Is your feature request related to a problem? Please describe.**
The courses' pages look like a mess. The windows are different sizes, not all lessons from each course have a description, some icons don't load, and some titles are missing.

**Describe the solution you'd like**
A renovated system for displaying the available lessons of each course, proper lesson descriptions, and making sure course icons and titles are visible correctly

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by GalaxyGamingBoy** [comment]
Issue has been fixed as per yesterdays commits AGAIN

**Comment by GalaxyGamingBoy** [comment]
Don't rush with issues before checking with the team

**Comment by odysseuskir** [comment]
As you may have seen, this is under discussion. We will share thoughts on the issue at Saturday's meeting.

**Comment by odysseuskir** [comment]
There are more issues that need to be resolved
