### ISSUE TITLE
Update the view section of courses

### ISSUE THREAD

**Issue by odysseuskir** [simplified-coding/simplified-coding#115]
**Is your feature request related to a problem? Please describe.**
Courses that cannot use the Simplified Code editor, such as Arduino, are in a mode code "view". The idea is great, but the font does not go along with the theme of the website, the print button prints the page and not the lesson content and the download button gets a .html version of the lesson, which is not ideal for beginner users.

**Describe the solution you'd like**
The font of the lesson content is updated, the print button prints the whole lesson and not the website, and the download button gets a .txt or .docx version of the lesson content.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by GalaxyGamingBoy** [comment]
@odysseuskir Won't implement proprietary docx standards till I die.
An HTML document is still ideal for beginners, i don't see the issue with it

**Comment by GalaxyGamingBoy** [comment]
As for the print button, issue has already been fixed in yesterdays commits

**Comment by GalaxyGamingBoy** [comment]
Also thinking about this, the user can PRINT to PDF, we can just do that instead of download
