### ISSUE TITLE
Create certificate manager

### ISSUE THREAD

**Issue by odysseuskir** [simplified-coding/simplified-coding#117]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
The certificate manager for Simplified Coding needs to be created, to issue signed certificates.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by GalaxyGamingBoy** [comment]
Certificate manager is: DONE.

**Comment by GalaxyGamingBoy** [comment]
TODO: DEPLOYMENT
