### ISSUE TITLE
Add descriptions in the lessons

### ISSUE THREAD

**Issue by Nikos1508** [simplified-coding/simplified-coding#119]
**Is your feature request related to a problem? Please describe.**
We have to describe what every lesson is for. 

**Additional context**
![image](https://github.com/simplified-coding/simplified-coding/assets/113199464/85000294-f7ef-44b3-9148-f23dbc71cd4c)

**Comment by odysseuskir** [comment]
Duplicate of #114

**Comment by GalaxyGamingBoy** [comment]
I digress, the issue clearly means the courses.json not the page

**Comment by GalaxyGamingBoy** [comment]
Actually nvm, i will just rephrase the other one

**Comment by odysseuskir** [comment]
💀
