### ISSUE TITLE
Promote certifications at the end of courses

### ISSUE THREAD

**Issue by odysseuskir** [simplified-coding/simplified-coding#134]
### Discussed in https://github.com/simplified-coding/simplified-coding/discussions/133

<div type='discussions-op-text'>

<sup>Originally posted by **odysseuskir** December 25, 2023</sup>
Simplified Coding offers certifications for Python and HTML/CSS, but they are not visible on the website. I propose we have a card on the end of each supported course, so people can get a certification.</div>

**Comment by Nikos1508** [comment]
We can have a pop-up (toast) in the bottom of the right side of the user's screen.
Like this: https://getbootstrap.com/docs/5.3/components/toasts/

**Comment by odysseuskir** [comment]
I think that's too subtle for a user to notice

**Comment by odysseuskir** [comment]
Part of #114
