### ISSUE TITLE
Create roadmap-like interface

### ISSUE THREAD

**Issue by odysseuskir** [simplified-coding/simplified-coding#83]
The current interface of Simplified Coding divides its courses in 3 directions. Basic Computer Programming, Web Development, and Robotics. However, with the addition of new courses, that system might turn out to be dysfunctional. That is why we will be creating a roadmap-like interface, similar to the interface of the well-known `roadmap.sh` website. The first modules will include our `Basic Computer Programming Terms` and `Basic Computer Concepts`. The next will be divided into the current directions. That will result in a more clear pathway for users to follow.

**Comment by Nikos1508** [comment]
This should be deleted! ! !

**Comment by GalaxyGamingBoy** [comment]
Progress in Simplified Coding Figma

**Comment by Nikos1508** [comment]
Also we should add the animated "Simplified Coding" above it in the home page.

**Comment by odysseuskir** [comment]
Which is?
